site_name: Ruth Lichterma (2025.1)
site_description: Documentação do projeto do grupo Betty Snyder de Qualidade de Software (2025.1), Turma 1

repo_url: https://github.com/FCTE-Qualidade-de-Software-1/2025-1-T01-RUTH-LICHTERMA/tree/main
repo_name: 2025-1-T01-RUTH-LICHTERMA

not_in_nav: |
  qrapid/dashboard_fixed.html


nav:
  - Home: index.md
  - Organização:
    - Backlog: organizacao/backlog.md
    - Registro de Reuniões: organizacao/reunioes.md
    - Tabela de Contribuição: organizacao/contribuicao.md
    - Métricas PSM-CID: organizacao/psm-cid.md
  - Fase 1:
    - Contextualização: contextualizacao.md
    - Q-rapid: qrapid/qrapid.md
  - Fases 2 e 3:
    - Objetivos: gqm/objetivos.md
    - Questões e Hipóteses: gqm/questoes.md
    - Abstraction Sheets: gqm/abstractionsheets.md
    - Definição das Métricas (GQM): gqm/metricas.md
  - Fase 4:
    - Avaliação das Métricas: gqm/avaliacao.md
    - Definição das Métricas (Q-Rapids): qrapid/metricas.md
    - Q-Rapids Dashboard: qrapid/dashboard.md


theme:
  name: material
  language: pt-BR
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  palette:
  - scheme: default
    toggle:
      icon: material/brightness-7 
      name: Clique para trocar para Modo Escuro
    primary: dark-blue

  - scheme: slate
    toggle:
      icon: material/brightness-4
      name: Clique para trocar para Alto Contraste
    primary: dark-blue

  - scheme: high-contrast
    primary: black
    accent: yellow
    toggle:
      icon: material/weather-cloudy-alert
      name: Clique para trocar para Modo Claro
    
  extra_css: [stylesheets/extra.css]